// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Treinu.Infrastructure.Data;

#nullable disable

namespace Treinu.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Treinu.Domain.Entities.AvaliacaoFisica.AvaliacaoFisica", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AlunoId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Data")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("AlunoId");

                    b.ToTable("AvaliacoesFisicas", (string)null);

                    b.HasDiscriminator<string>("Tipo");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Treinu.Domain.Entities.AvaliacaoFisica.Medida", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Chave")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid?>("QuestionarioId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Valor")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("QuestionarioId");

                    b.ToTable("Medidas", (string)null);
                });

            modelBuilder.Entity("Treinu.Domain.Entities.Certificado", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ArquivoPdf")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DataUpload")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid?>("TreinadorId")
                        .HasColumnType("uuid");

                    b.Property<bool>("Validado")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("TreinadorId");

                    b.ToTable("Certificados", (string)null);
                });

            modelBuilder.Entity("Treinu.Domain.Entities.Contato", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Descricao")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("NomeExibicao")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Plataforma")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("Principal")
                        .HasColumnType("boolean");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid?>("UsuarioId")
                        .HasColumnType("uuid");

                    b.Property<string>("Valor")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Contatos", (string)null);
                });

            modelBuilder.Entity("Treinu.Domain.Entities.Convite", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("ExpiraEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Perfil")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("Token")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("TreinadorId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Email");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("TreinadorId");

                    b.ToTable("Convites", (string)null);
                });

            modelBuilder.Entity("Treinu.Domain.Entities.Credencial", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("RefreshToken")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime?>("RefreshTokenExpiryTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Senha")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("TipoUsuario")
                        .IsRequired()
                        .HasColumnType("varchar(30)");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("UsuarioId")
                        .IsUnique();

                    b.ToTable("Credenciais", (string)null);
                });

            modelBuilder.Entity("Treinu.Domain.Entities.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("AceiteTermoAdesao")
                        .HasColumnType("boolean");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Genero")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("NomeCompleto")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Perfil")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Cpf")
                        .IsUnique();

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Usuarios", (string)null);

                    b.HasDiscriminator<string>("Perfil");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Treinu.Domain.Entities.AvaliacaoFisica.Documento", b =>
                {
                    b.HasBaseType("Treinu.Domain.Entities.AvaliacaoFisica.AvaliacaoFisica");

                    b.Property<string>("Arquivo")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasDiscriminator().HasValue("DOCUMENTO");
                });

            modelBuilder.Entity("Treinu.Domain.Entities.AvaliacaoFisica.Questionario", b =>
                {
                    b.HasBaseType("Treinu.Domain.Entities.AvaliacaoFisica.AvaliacaoFisica");

                    b.Property<double>("Altura")
                        .HasColumnType("double precision");

                    b.Property<string>("Classificacao")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<double>("Imc")
                        .HasColumnType("double precision");

                    b.Property<double>("Peso")
                        .HasColumnType("double precision");

                    b.HasDiscriminator().HasValue("QUESTIONARIO");
                });

            modelBuilder.Entity("Treinu.Domain.Entities.Administrador", b =>
                {
                    b.HasBaseType("Treinu.Domain.Entities.Usuario");

                    b.HasDiscriminator().HasValue("ADMIN");
                });

            modelBuilder.Entity("Treinu.Domain.Entities.Aluno", b =>
                {
                    b.HasBaseType("Treinu.Domain.Entities.Usuario");

                    b.Property<string>("Objetivo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid?>("TreinadorId")
                        .HasColumnType("uuid");

                    b.HasIndex("TreinadorId");

                    b.HasDiscriminator().HasValue("ALUNO");
                });

            modelBuilder.Entity("Treinu.Domain.Entities.Treinador", b =>
                {
                    b.HasBaseType("Treinu.Domain.Entities.Usuario");

                    b.PrimitiveCollection<string>("Especializacoes")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.HasDiscriminator().HasValue("TREINADOR");
                });

            modelBuilder.Entity("Treinu.Domain.Entities.AvaliacaoFisica.AvaliacaoFisica", b =>
                {
                    b.HasOne("Treinu.Domain.Entities.Aluno", null)
                        .WithMany("AvaliacaoFisica")
                        .HasForeignKey("AlunoId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Treinu.Domain.Entities.AvaliacaoFisica.Medida", b =>
                {
                    b.HasOne("Treinu.Domain.Entities.AvaliacaoFisica.Questionario", null)
                        .WithMany("Medidas")
                        .HasForeignKey("QuestionarioId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Treinu.Domain.Entities.Certificado", b =>
                {
                    b.HasOne("Treinu.Domain.Entities.Treinador", null)
                        .WithMany("Certificados")
                        .HasForeignKey("TreinadorId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Treinu.Domain.Entities.Contato", b =>
                {
                    b.HasOne("Treinu.Domain.Entities.Usuario", null)
                        .WithMany("Contato")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Treinu.Domain.Entities.Convite", b =>
                {
                    b.HasOne("Treinu.Domain.Entities.Treinador", "Treinador")
                        .WithMany("Convites")
                        .HasForeignKey("TreinadorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Treinador");
                });

            modelBuilder.Entity("Treinu.Domain.Entities.Credencial", b =>
                {
                    b.HasOne("Treinu.Domain.Entities.Usuario", "Usuario")
                        .WithOne("Credencial")
                        .HasForeignKey("Treinu.Domain.Entities.Credencial", "UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Treinu.Domain.Entities.Aluno", b =>
                {
                    b.HasOne("Treinu.Domain.Entities.Treinador", "Treinador")
                        .WithMany("Alunos")
                        .HasForeignKey("TreinadorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Treinador");
                });

            modelBuilder.Entity("Treinu.Domain.Entities.Usuario", b =>
                {
                    b.Navigation("Contato");

                    b.Navigation("Credencial");
                });

            modelBuilder.Entity("Treinu.Domain.Entities.AvaliacaoFisica.Questionario", b =>
                {
                    b.Navigation("Medidas");
                });

            modelBuilder.Entity("Treinu.Domain.Entities.Aluno", b =>
                {
                    b.Navigation("AvaliacaoFisica");
                });

            modelBuilder.Entity("Treinu.Domain.Entities.Treinador", b =>
                {
                    b.Navigation("Alunos");

                    b.Navigation("Certificados");

                    b.Navigation("Convites");
                });
#pragma warning restore 612, 618
        }
    }
}
